[chore] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (111)
Module build failed (from ../node_modules/sass-loader/lib/loader.js):                                                                        friendly-errors 19:32:12
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (111)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/Users/ikeda/src/shogi-extend/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/ikeda/src/shogi-extend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/ikeda/src/shogi-extend/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at loadLoader (/Users/ikeda/src/shogi-extend/nuxt_side/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:18:17)